### PR TITLE
updated some licenses to ASF and removed naxsi module

### PR DESCRIPTION
**Pull request by ddragosd**
This issue relates to #288.

Changes:
- [x] Updated files containing Adobe's MIT license to Apache 2.0 license
- [x] Removed NAXSI lib b/c it's GPL [licensed](https://github.com/nbs-system/naxsi/issues/221) and it [can't be included](https://www.apache.org/licenses/GPL-compatibility.html) in Apache licensed projects.

### CODE REVIEW

**Comment by ddragosd** [comment]
I see the build fails with 
```
Unsupported parameters for (docker_container) module: userns_mode
```

This is not related to the changes in the current PR, but rather an ansible module issue; I’ll check for a fix regardless, early next week.

**Comment by mhamann** [comment]
Yeah, I started to look into it, but ran out of time. If you get time, that'd be great.

**Comment by csantanapr** [comment]
I think is a problem with recent change to update to ansible 2.5
Update tools/travis/setup.sh and is better to use the setup.sh from core repo that way we don’t have to install ansible from this repo

**Comment by ddragosd** [comment]
thanks @csantanapr I'll give it a try now.

**Comment by ddragosd** [comment]
solved the build issues in #295 . @mhamann , @csantanapr may I ask for your help to review that one ?

**Comment by ddragosd** [comment]
> Update tools/travis/setup.sh and is better to use the setup.sh from core repo that way we don’t have to install ansible from this repo

@csantanapr I'm wondering how we can implement this in the sub-projects such as this one. Have the setup clone the entire https://github.com/apache/incubator-openwhisk and run the [setup.sh](https://github.com/apache/incubator-openwhisk/blob/master/tools/travis/setup.sh) from it first ?

**Comment by csantanapr** [comment]
Yes we already cloning the main repo we just need to use setup.sh from it

**Pull request merged**
