### PR TITLE
Adding provisions for building s390x (Linux on Z) images of openwhisk-apigateway

### PR DESCRIPTION
**Pull request by jonpspri**
As a subcategory of work I'm doing to deploy a working OpenWhisk on Linux on Z (s390x) architecture, I've recently forked the openwhisk-apigateway platform and edited its Dockerfile so it would build an image cleanly on s390x.

I've yet to execute test suites against the image, but it does build cleanly and start cleanly from the openwhisk ansible scripts.  The approach I took was to use M4 macro processor to make adjustments where needed for the s390x architecture:

1. The alpine:3.6 images needs to come from the s390x user ID (which is the biggest problem with Docker, IMO)
2. LuaJIT has to be build for Linux on Z outside of the version that ships with OpenRESTY.
3. The JIT option is not available for Linu on Z for PCRE (to the best of my knowledge and Google ability) 
4.  To avoid more compiling debugging, I used APK to acquire JQ and dumb-init.
5.  Optimizations of the APK and Git downloads to reduce load on storage and cache management woes (apk --no-cache and curl piping directly to tar).

I've included a build_image.sh script to show how the Dockerfile.m4 is processed; I haven't completely thought through how to make that ready for prime-time, but I'm sure there will be feedback anyway.

### CODE REVIEW

**Comment by jonpspri** [comment]
Hi, thanks for the feedback.  Let me go through it point-by-point:

I think I have a signed ICLA from a different project, but I'll double-check and clear it up.

1.  I can replace the profiling scripts.  The fact that they had leading dots and so on confused me as to their true purpose and whether they were excess baggage or not.

2.  I know the build is failing, but in part that's because of the need to pre-process the Dockerfile, which the travis scripts don't yet account for.  I wanted to deal with the "which pre-processor" question first.

3.  I'll consider whether we could use an argument instead of macro processing.  It's conceivable, for example to just use 'uname -m' to make the decision in shell logic.  Nothing I can do about the FROM line, alas.

4.  I used m4 because it's highly likely to be available in any build environment and it does a lot of pre-processory stuff.  I'll take a look and handlebars and mustache -- I am not proud.  If #3 gets down to one line, we may be able to get away with sed :)

I've got a few more TODO's to trim down the number of layers in the Dockerfile, so I'll see what I can do there.  Probably will set up another commit this evening at some point.

**Comment by taylorking** [comment]
Thanks, the profiling scripts just add some things to the dockerfile to make it easier to run the systemtap profiling utilities. Because we use systemtap inside of a docker container, we need to run both with --privileged and have matching kernel headers for the hosts kernel. I picked ubuntu as a base image because it is easy to simply do `sudo apt-get update && sudo apt-get install linux-headers-$(uname -r)`. Inside the repo there is a script `build_profiling.sh` that will generate a new dockerfile decorated with some of the things you need to run systemtap scripts. I am open to any suggestions you have on this, it would be really neat to use a preprocessor to generate this dockerfile instead of having to just use pattern replacement on the file.

**Comment by jonpspri** [comment]
I unwound the m4 by using some scripting to test 'uname -m' in the Dockerfile and do the architecture-specific work inline.  It means there will be a No-op layer for the LuaJIT build when running on x86_64, but we can live with that.

At the end of the day, the only line left to be templated was the FROM line -- so I set up the build_image.sh script I purloined from another project to use 'sed' for that.  Now I just re-read your comment and realized I may have switched the base image to Alpine in a fit of size-saving; I'll switch it back until we figure out how to do profiling on a smaller image.

My base concern is that OpenWhisk is a horde of Docker images and the less memory/storage we use, the lower the load on the Virtual Memory system.  Hence my near-obsesion with optimization.

The included LuaJIT with OpenResty does not support s390x -- the Linux on Z guys support their own fork which is what I'm downloading.  The --with-luajit=/path is expecting a path to a compiled library.  (I tried just pointing it to source.)  Not the best documentation in the OpenResty configure script.  

Next step is to cross-test this build on my x86_64 system (aka docker-machine on my Mac) then do the needful to get Travis to test the build script.

How do you handle tagging and pushing of the Docker images?  I have some provisions in my build script, but I expect they'll disappear soon :)

**Comment by taylorking** [comment]
[Here](https://github.com/apache/incubator-openwhisk-apigateway/blob/master/tools/travis/deploy.sh) is where the image gets pushed up to dockerhub. I I think we upload it as openwhisk/apigateway:$TRAVIS_TAG

**Comment by jonpspri** [comment]
Ha!  I figured out how to get the last bits and pieces into the Makefile.  I'm going to take a quick peek at how profiling is running ... we may be able to get that working on s390 as well.

**Comment by taylorking** [comment]
The problem with using the headers for the alpine kernel is that unless you are running alpine on your host, they wont be an exact match for the kernel you are running.

**Comment by jonpspri** [comment]
Got it.  Okay, let me see what I can do to make the revised Dockerfile not break the profiling script.

**Comment by taylorking** [comment]
What do you think about [this](https://github.com/apache/incubator-openwhisk-apigateway/pull/245) change? Reduced the number of docker layers from 33 to 15.

**Comment by jonpspri** [comment]
That change hits the string of ENVs and 'opm gets' that were at the heart of the problem.  I'd consider moving all the version numbers up to the one ENV statement (so they can still be overridden from the build command) and you might choose to run 'opm get' as a single process with the list of files.

I think there may be some natural stopping points between installing components -- they don't ALL need to be jammed together into a monolithic RUN stanza.  A few extra layers is okay, just so long as the /tmp directory gets cleaned up at the end of each RUN stanza.  I think of each stanza as a mixin -- eventually, we'll be building Dockerfiles by including different components.

Consider getting 'jq' and 'dumb-init' from the repositories.  Need to check on whether dumb-init is available for the Ubuntu profiling, though.

**Comment by jonpspri** [comment]
Okay, huge changes over the last 1-2 days:

1.  All profiling logic is now in the Dockerfile or the Makefile.  I introduced the environment variable DOCKER_DISTRO to the make to override the alpine/ubuntu choice, but kept the same default distro for regular builds (alpine) vs. profiling builds (ubuntu).  Still considering just mounting kernel headers as a volume rather than re-sourcing them into the Docker image.

2.  Package management (get and remove) is all in the Dockerfile, but is bracketed by if-elif-else-fi logic to use the appropriate packages and package manager.  I'm not thrilled by this approach, but barring a universal package manager, it seemed to me to be the most maintainable approach.  The $PROFILE build argument gets tested at package get time and OpenResty configure time to ensure extra things happen.

3.  In a couple places, architecture tests have been introduced to deal with idiosynchracies of the s390x environment (mostly LuaJIT).  I decided to always pre-compile LuaJIT so it could have its own stanza and the OpenResty stanza would run faster when needed.

4.  There are still two 'sed'-based manipulations of the Dockerfile:  (a) The image is manipulated for architecture (s390x vs everything else) and distro (alpine vs ubuntu), and (b) Lines that begin with '#PROFILE' are uncommented for profiling (WORKDIR and COPY lines right now).

PLEASE TEST PROFILING (or give me an idea of how you run profiling so I can run locally on my ubuntu VM).  I have to run to a meeting now...

**Comment by jonpspri** [comment]
So I'm working on the profiling headers problem now.  I've had to move the docker build into a subdirectory, which is fine when the Makefile is used to build it.  As a result, I've broken the Travis CI -- no big surprise there.  I'll figure out where it's breaking and what I can do to make this more robust.  I expect we'll catch up on Slack early next week to discuss which pieces of this work you want to integrate into the main build.

**Pull request closed without merging**
