### PR TITLE
self optimizing routing code

### PR DESCRIPTION
**Pull request by taylorking**
Optimizes call to routing with a prefix tree rather than just getting all products in a tenant and iterating over them trying to match the pattern.

I called this on one of our tenants with a bunch of apis: 

Optimizations off:
```
Running 5s test @ http://9.37.200.19:32801/api/a27b9526a7c9d44fd1f2550d70651d7509ed3e43b3add35af69f20ea46f5c8d9/helloWorld/36717
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.23s   378.84ms   4.97s    62.71%
    Req/Sec    38.62     22.02    80.00     69.23%
  59 requests in 5.05s, 62.57KB read
Requests/sec:     11.69
Transfer/sec:     12.40KB
```

Optimizations On: 

```
Running 5s test @ http://9.37.200.19:32803/api/a27b9526a7c9d44fd1f2550d70651d7509ed3e43b3add35af69f20ea46f5c8d9/helloWorld/36717
  2 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.68s     1.14s    4.03s    51.22%
    Req/Sec   354.18    312.17     1.22k    69.23%
  2384 requests in 5.05s, 2.47MB read
Requests/sec:    472.09
Transfer/sec:    500.63KB
```

### CODE REVIEW

**Comment by taylorking** [comment]
Got a weird flame graph out of this one.. 
out

**Comment by taylorking** [comment]
under optimal conditions this is really really fast 

```
  8 threads and 10000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   121.20ms  150.71ms 626.33ms   68.84%
    Req/Sec     1.40k     1.69k    7.23k    86.29%
  82390 requests in 10.06s, 20.74MB read
  Socket errors: connect 8987, read 0, write 0, timeout 0
Requests/sec:   8190.09
Transfer/sec:      2.06MB
```

**Comment by mhamann** [comment]
@taylorking could you rebase this? We'll see about merging it this coming week.

**Comment by taylorking** [comment]
Let's wait a bit before merging this, there are a couple of our tests failing I think because of cache invalidation timing, want to get those passing before we merge this

**Comment by taylorking** [comment]
Tests are looking good now, I want to clean up the code so that it preserves alex's stuff for cloud foundry apps

**Comment by mhamann** [comment]
@taylorking looks like there are a couple of failing unit tests

```
not ok 19 - Testing routing module should find the correct redis key
# scripts/lua/routing.lua @ 45
# Failure message: ...penwhisk-apigateway/tests/../scripts/lua/routing.lua:115: attempt to compare number with nil
not ok 20 - Testing routing module should return nil if redis key doesn't exist
# scripts/lua/routing.lua @ 56
# Failure message: ...penwhisk-apigateway/tests/../scripts/lua/routing.lua:115: attempt to compare number with nil
not ok 21 - Testing routing module should find correct key when basePath is "/"
# scripts/lua/routing.lua @ 64
# Failure message: ...penwhisk-apigateway/tests/../scripts/lua/routing.lua:115: attempt to compare number with nil
not ok 22 - Testing routing module should find correct key when resourcePath is "/"
# scripts/lua/routing.lua @ 75
# Failure message: ...penwhisk-apigateway/tests/../scripts/lua/routing.lua:115: attempt to compare number with nil
```

**Comment by mhamann** [comment]
Seems like this has stabilized. @taylorking can you rebase? Do you feel this is good to go?

**Pull request merged**
